<a href="https://colab.research.google.com/github/PaolaVergaraHernandez/MachineLearning/blob/main/Practica_1_Frutas_U3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Machine y Deep Learning
# Unidad 3
## Práctica 1: **KNN Frutas**
### Docente: Dr. Jose Gabriel Rodriguez Rivas
### Alumno: Paola Vergara Hernandez

In [ ]:
# Importar librerias
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
frutas = pd.read_csv("frutas.csv")
frutas.head()

   fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [ ]:
X = frutas[["height", "width", "mass", "color_score"]]

y= frutas["fruit_name"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
clasificacion_KNN = KNeighborsClassifier(n_neighbors=1)

In [ ]:
clasificacion_KNN = KNeighborsClassifier(n_neighbors=1)
clasificacion_KNN.fit(X_train, y_train)
print("Precision del clasificador en fase de entrenamiento",
      clasificacion_KNN.score(X_train, y_train))

Precision del clasificador en fase de entrenamiento 1.0

In [ ]:
y_pred = clasificacion_KNN.predict(X_test)
print("Reporte de métricas del clasificador: \n", classification_report(y_test, y_pred))

print ("Precisión:", clasificacion_KNN.score(X_test, y_test))

Reporte de métricas del clasificador:
               precision    recall  f1-score   support

       apple       0.50      0.33      0.40         6
       lemon       1.00      0.67      0.80         6
    mandarin       1.00      1.00      1.00         4
      orange       0.38      0.75      0.50         4

    accuracy                           0.65        20
   macro avg       0.72      0.69      0.68        20
weighted avg       0.72      0.65      0.66        20

Precisión: 0.65

In [ ]:
print ("Matriz de confusión: \n", confusion_matrix(y_test, y_pred), "\n")

Matriz de confusión:
 [[2 0 0 4]
 [1 4 0 1]
 [0 0 4 0]
 [1 0 0 3]]

In [ ]:
from sklearn.inspection import permutation_importance
result = permutation_importance(clasificacion_KNN, X_test, y_test, n_repeats=30,
                                random_state=42)

importancia = pd.DataFrame({
    "Variable": X.columns,
    "Importancia": result.importances_mean,
    "Desviación": result.importances_std,
}).sort_values(by="Importancia", ascending=False)
print(importancia)

      Variable  Importancia  Desviación
2         mass     0.393333    0.108577
3  color_score    -0.001667    0.008975
0       height    -0.023333    0.044222
1        width    -0.048333    0.039756

In [ ]:
import plotly.express as px
fig = px.bar(importancia, x="Variable", y="Importancia", error_y="Desviación", title="Importancia de características (KNN - Permutation Importance)",
text_auto=".3f", color= "Variable")
fig.update_layout(width=600,height=400)
fig.show()

In [ ]:
clasificacion_KNN3 = KNeighborsClassifier(n_neighbors=3)
clasificacion_KNN3.fit(X_train, y_train)
print("Precision del clasificador en fase de entrenamiento",
      clasificacion_KNN3.score(X_train, y_train))

Precision del clasificador en fase de entrenamiento 0.7948717948717948

In [ ]:
y_pred = clasificacion_KNN3.predict(X_test)
print("Reporte de métricas del clasificador: \n", classification_report(y_test, y_pred))

print ("Precisión:", clasificacion_KNN3.score(X_test, y_test))

Reporte de métricas del clasificador:
               precision    recall  f1-score   support

       apple       0.80      0.67      0.73         6
       lemon       0.33      0.50      0.40         6
    mandarin       0.00      0.00      0.00         4
      orange       0.50      0.75      0.60         4

    accuracy                           0.50        20
   macro avg       0.41      0.48      0.43        20
weighted avg       0.44      0.50      0.46        20

Precisión: 0.5

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

In [ ]:
print ("Matriz de confusión: \n", confusion_matrix(y_test, y_pred), "\n")

Matriz de confusión:
 [[4 1 0 1]
 [1 3 0 2]
 [0 4 0 0]
 [0 1 0 3]]

In [ ]:
clasificacion_KNN5 = KNeighborsClassifier(n_neighbors=5)
clasificacion_KNN5.fit(X_train, y_train)

print("Precision del clasificador en fase de entrenamiento",
      clasificacion_KNN5.score(X_train, y_train))

Precision del clasificador en fase de entrenamiento 0.717948717948718

In [ ]:
y_pred = clasificacion_KNN5.predict(X_test)
print("Reporte de métricas del clasificador: \n", classification_report(y_test, y_pred))
print ("Precisión:", clasificacion_KNN5.score(X_test, y_test))

Reporte de métricas del clasificador:
               precision    recall  f1-score   support

       apple       0.75      0.50      0.60         6
       lemon       0.33      0.50      0.40         6
    mandarin       0.00      0.00      0.00         4
      orange       0.43      0.75      0.55         4

    accuracy                           0.45        20
   macro avg       0.38      0.44      0.39        20
weighted avg       0.41      0.45      0.41        20

Precisión: 0.45

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

In [ ]:
print("Matriz de confusion: \n",confusion_matrix(y_test, y_pred),"\n")

Matriz de confusion:
 [[3 1 0 2]
 [1 3 0 2]
 [0 4 0 0]
 [0 1 0 3]]

In [ ]:
for k in range (1,20):
  knn = KNeighborsClassifier(n_neighbors=k)
  knn.fit(X_train, y_train)
  y_pred = knn.predict(X_test)
  print(f"k={k} Precisión: {knn.score(X_test, y_test):.2f}")

k=1 Precisión: 0.65
k=2 Precisión: 0.45
k=3 Precisión: 0.50
k=4 Precisión: 0.50
k=5 Precisión: 0.45
k=6 Precisión: 0.45
k=7 Precisión: 0.50
k=8 Precisión: 0.55
k=9 Precisión: 0.55
k=10 Precisión: 0.55
k=11 Precisión: 0.55
k=12 Precisión: 0.50
k=13 Precisión: 0.50
k=14 Precisión: 0.45
k=15 Precisión: 0.50
k=16 Precisión: 0.45
k=17 Precisión: 0.45
k=18 Precisión: 0.35
k=19 Precisión: 0.30

In [ ]:
from sklearn.preprocessing import StandardScaler

X = frutas[["height", "width", "mass", "color_score"]]
y = frutas["fruit_name"]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

# Inicializar y aplicar el escalador
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Entrenar el modelo con los datos ESCALADOS
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_scaled, y_train)

# Realizar las predicciones con los datos de prueba escalados
y_pred_scaled = knn.predict(X_test_scaled)

print("\nReporte de clasificacion:")
print(classification_report(y_test, y_pred_scaled))

Reporte de clasificacion:
              precision    recall  f1-score   support

       apple       1.00      0.80      0.89         5
       lemon       1.00      1.00      1.00         4
    mandarin       1.00      1.00      1.00         1
      orange       0.83      1.00      0.91         5

    accuracy                           0.93        15
   macro avg       0.96      0.95      0.95        15
weighted avg       0.94      0.93      0.93        15

In [ ]:
print ("Matriz de confusion: \n", confusion_matrix(y_test, y_pred_scaled), "\n")

Matriz de confusion:
 [[4 0 0 1]
 [0 4 0 0]
 [0 0 1 0]
 [0 0 0 5]]

In [ ]:
from sklearn.inspection import permutation_importance

# Usamos el modelo 'knn' que fue el que entrenamos con datos escalados
result = permutation_importance(knn, X_test_scaled, y_test, n_repeats=30,
                                random_state=42)

importancia = pd.DataFrame({
    "Variable": X.columns,
    "Importancia": result.importances_mean,
    "Desviación": result.importances_std,
}).sort_values(by="Importancia", ascending=False)

importancia

      Variable  Importancia  Desviación
0       height     0.262222    0.080615
1        width     0.188889    0.075195
3  color_score     0.182222    0.103184
2         mass     0.037778    0.061303

In [ ]:
import plotly.express as px
fig4 = px.bar(importancia, x="Variable", y="Importancia",
              error_y="Desviación", title="Importancia de características (KNN - Permutation Importance)",
text_auto=".3f", color= "Variable")
fig4.update_layout(width=600,height=400)
fig4.show()

In [ ]:
fruta1 = [[5.5, 2.2, 150, 0.70]]
print("la fruta 1 con caracteristicas ", fruta1, " es de tipo", knn.predict(fruta1))

la fruta 1 con caracteristicas  [[5.5, 2.2, 150, 0.7]]  es de tipo ['orange']

In [ ]:
frutas = [[5.5, 2.2, 120, 0.70], [2, 2, 160, 0.50]]
print("las frutas con caracteristicas ", frutas, " son de tipo", knn.predict(frutas))

las frutas con caracteristicas  [[5.5, 2.2, 120, 0.7], [2, 2, 160, 0.5]]  son de tipo ['orange' 'orange']